### ISSUE TITLE
OR query

### ISSUE THREAD

**Issue by fmmsilva** [frankred/node-full-text-search-light#3]
Is it possible to do an 'OR' query?
Like 'cars or bikes'

**Comment by frankred** [comment]
No that is currently not possobile.

But what you can just do two search queries and concat those.

```
var result_a = search.search('paul');
var result_b = search.search('maria');
var result = result_a.concat(result_b);
```

**Comment by fmmsilva** [comment]
What about the scoring?

**Comment by frankred** [comment]
Nope :(
