### ISSUE TITLE
Question: is this vector space model?

### ISSUE THREAD

**Issue by alexge233** [frankred/node-full-text-search-light#4]
Hi, just a question:

Is this a vector space model or using feature vectors?
Can I get the index score to the matching pattern?

Best regards,
Alex

**Comment by frankred** [comment]
Hi @alexge233  sorry I'm not very deep into machine learning so I cannot answer your question 100% correctly. But I think it's none of the vector thing. Also there is no index score. There is no fuzzy logic so the searched text fits 100% or fits 0%.

**Comment by alexge233** [comment]
@frankred Thanks for the reply!
