### ISSUE TITLE
Npm is crashing during full-text-search indexing.

### ISSUE THREAD

**Issue by Deepak275** [frankred/node-full-text-search-light#5]
Hi everyone, i am using a npm package full-text-search-light package for implementing full text search. On instantiating it, it is taking a index parmeter. I am facing the same error Error: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory. when i am using index_amount 12 for indexing the data in memory. when i am bringing it down to the 6 or less, it is working fine. node version is
v6.3.1. Please help me.

**Comment by frankred** [comment]
Ok seems that memory runs out. How many entries do you add? The less indexes you are using the less memory is taken. But the slower your searches can get.

Edit: This full-text-search only runs in memory, so if your data is too big then you may run into this problem. You should think about a file or server based solution e.g.: 
- http://lucene.apache.org/solr/
- http://sphinxsearch.com/

**Comment by Deepak275** [comment]
hi @frankred, thanks for the reply. Let me provide you the whole scenario, i am parsing a 32mb xls file and storing in memory. It has around 132k entries, each with 10 columns.When i am instantiating with index_count 12 or more it is show Error: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory. 
When i am reducing it to 10 it is working fine. I don't think 32mb is not enough memory for a ram of 8gb ?

**Comment by frankred** [comment]
@Deepak275 
Can you provide an example of one entry as JSON object that you pass to the `add` function. Then I can try to reproduce the problem.

**Comment by Deepak275** [comment]
@frankred 
I am adding an array of objects, with each objects has this property: 
 {  
     bank = options.bank;
     ifsc = options.ifsc;
     micr = options.micr;
     branch = options.branch;
     address = options.address;
     contact = options.contact;
     city = options.city;
    district = options.district;
    state = options.state
}
It is basically details of a bank's branch.

**Comment by frankred** [comment]
Thank you, I reproduced the same problem. 
After stepping deeper to it, I found out that this is not really a bug, all this happens because on every "string" or "object" you add to the search, there may a lot of objects are be created within the full-text-search:

For example:

``` js
var fulltextsearchlight = require('full-text-search-light');
var search = new fulltextsearchlight({
  ignore_case: false,   // default = true, Ignore case during all search queries
  index_amount: 4   // default = 12, The more indexes you have, the faster can be your search but the slower the 'add' method  gets
});

search.add("Hello World");
```

This creates (index_amount=4)  37 index objects (its a key e.g. "Hell" and a reference id e.g.: 4711)

```
full-text-search-light Parts for "Hello World": ["H","e","l","o"," ","W","r","d"]  => 8 indexes
full-text-search-light Parts for "Hello World": ["He","el","ll","lo","o "," W","Wo","or","rl","ld"] => 11 indexes
full-text-search-light Parts for "Hello World": ["Hel","ell","llo","lo ","o W"," Wo","Wor","orl","rld"]=> 9 indexes
full-text-search-light Parts for "Hello World": ["Hell","ello","llo ","lo W","o Wo"," Wor","Worl","orld"]  => 9 indexes
```

8+11+9+9 = 37

Indexes are only created if they do not exists yet.

so 

```
search.add("Hello World");  // creates 37 index objects
search.add("Hello World");  // creates 0 index objects, but the existing indexes are getting modified
```

So if you now add a lot of different kind of words a huge bunch of objects will be created and we can get some problems with our memory. To solve this momery problem you can down scale your `index_amount`, like you already did :). Or you can do this (increase node memory e.g.: 8 GB):  

```
node --max-old-space-size=8192 index.js
```

The only disadvantage you can get if you reduce your `index_amount` that your search can get very slow. So you shouldn't go less then `index_amount=2`.

Hope this helps you!

**Comment by Deepak275** [comment]
Oh great @frankred ,  you have really explained in great details, i am overwhelmed :).  Hah, ok coming back to the topic, yeah i have tried to find the solution and yeah some people in stackoverflow suggest to increase the node -max-old-space-size. Actually i am new to node, so can u tell how i can check some of the default value of the node config value like this -max-old-space-size. Thanks for the your time and efforts, really appriciate it. :)

**Comment by frankred** [comment]
No problem for that ;)

@Deepak275  sorry I do not know too :smile:
