### ISSUE TITLE
Cannot use with Rollup

### ISSUE THREAD

**Issue by krabbypattified** [frankred/node-full-text-search-light#7]
I get this error
```
Error: Identifier 'debug' has already been declared
```
when I run Rollup because `debug` is declared twice in `index.js` for no reason.
```
var debug = require('debug');
var jsonfile = require('jsonfile');
var merge = require('merge');
var debug = debug('full-text-search-light');
```

**Comment by frankred** [comment]
You are right! I've just fixed this duplicate variable bug and released a new version:
https://www.npmjs.com/package/full-text-search-light (0.0.18)

Install version 0.0.18:  `npm install full-text-search-light@0.0.18 --save`

Does the error still occur? @krabbypattified

**Comment by krabbypattified** [comment]
It seems to be fixed, thank you @frankred  :)
